USE [master]
GO

/****** Object:  Database [BMS]    Script Date: 07-10-2021 17:33:49 ******/
CREATE DATABASE [BMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BMS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BMS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [BMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BMS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BMS] SET RECOVERY FULL 
GO

ALTER DATABASE [BMS] SET  MULTI_USER 
GO

ALTER DATABASE [BMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BMS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BMS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BMS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BMS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BMS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BMS] SET  READ_WRITE 
GO

